name: Backup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Start backup
      run: |
        git rm revanced-cli*.zip revanced-patches*.zip revanced-manager*.zip
        python dl-all.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        NOW=$(date +%F_%T_%Z)
        git add .
        git commit -m "[$NOW] Backup all revanced repositories"
        git push
