name: Backup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start backup
      run: |
        python dl-all.py
        echo "NOW=$(date +%F_%T_%Z)" >> $GITHUB_ENV

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "[${{ env.NOW }}] Backup all revanced repositories"
